
default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :deploy do
    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end

platform :android do
  desc "Deploy to Google Play"
  lane :deploy do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "android"
    )
    upload_to_play_store(
      track: "internal",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )
  end
end
